services:
  mysql:
    image: docker.io/library/mysql:8.0
    container_name: mysql-dev
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  rabbitmq:
    image: docker.io/library/rabbitmq:3-management
    container_name: rabbitmq-dev
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  mysql-data:
  rabbitmq-data:
